### PR TITLE
Heat Map Project

### PR DESCRIPTION
**Pull request by rootDEV2990**
Please help us review our Heat Map from the UX - UI Design project. We have validated with W3s HTML validator and corrected sticklerci errors.

### CODE REVIEW

**Comment by rootDEV2990** [comment]
Closed and reopened to activate SticklerCI plugin.

**Comment by uryelah** [comment]
Hello **Miguel Enciso Sanchez** & **Roberto Pérez Jiménez**, I'm Sarah, your reviewer for this PR 👩‍🚀  

**Great job for this first code review 🎇🎆**
You are almost there, there are some misconceptions about the project we need to fix though.

---------    

**Great job at: 🥇** 
- positioning the main text of the page
- using semantic HTML
- adding a screencap in the readme
- adding the rotate effect to rotated images
- paying attention to border-radius.

**You still need to fix some minor issues below before you can move to the next project**

---------

### Required changes 🛠 

- [x] Please don't use `id`s for styling in CSS, use classes for that. [Read here why](https://dev.to/clairecodes/reasons-not-to-use-ids-in-css-4ni4).

- [x] The `.feat-post` divs should be `<article>s`. That goes for most divs inside sections. [Read this article ](https://bitsofco.de/sectioning-content-in-html5/)to understand when an element should be an `<article>`.

- [x] Your design tear-down should be all in shades of grey. Take out any color your style.

- [x] Your design tear-down should not include any actual images, you can use grey blocks to represent them.

- [x] Don't use the black borders to separate blocks, 

You can check [this project](https://rawcdn.githack.com/santiago-rodrig/design-teardown/0b0eaaf8a4a5bc584ef1a2c2715a0a66e209cd80/index.html) as a guide, yours don't need to be as detailed but it could serve as guidance.

---------

Remember, you should use the greyscale to point to how much the visual elements on the page get your eye's attention. In this situation, surounded by grey, color gets a lot of attention and that defeats the purpose of the exercise.

**Please fix the required changes 👷  before asking for a new code review**

---------

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Great work @rootDEV2990 and @LoboArkano :+1: 
You have done a really great job, however, please consider that the changes and requirements proposed by the my colleague have not all been met. 

Please give the list a second look. Also, consider taking a look at this [project](https://rawcdn.githack.com/carlosprietobarron/smashingmag/2af4d72ed7e3f7e857d8bdc8e2b8637ec1a6bf33/index.html) to get an idea of what is expected.

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
# Project Approved :thumbsup:
## Hello Team ,  You have done a great job with this project. :clap:

**Review by kobiyoyo — APPROVED** [review]
Project approved

**Pull request merged**
